name: Run Tests

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v4
      with:
        submodules: true
    - name: List BioCro files
      run: |
        git branch
        ls -lR biocro-lib/src
    - name: Build all targets
      run: |
        cmake -B build -S .
        cmake --build build
    - name: Run Tests
      run: |
        cd build
        ctest
