name: Run Tests

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Clone GTest
      run:  git clone https://github.com/google/googletest.git -b v1.14.0
    - name: Install gtest manually
      working-directory: ./googletest
      run:  sudo apt install python3-pip &&
            cmake . &&
            make &&
            sudo make install
    - name: Check out repository
      uses: actions/checkout@v3
      with:
        submodules: true
    - name: Build BioCro
      run: |
        cd biocro-lib/src
        make
    - name: Build DAWN app
      run: |
        cd app
        make use_local_schema_file=true main
    - name: Build Tests
      run: |
        cd tests
        make
    - name: Run Tests
      run: |
        cd tests
        ./test_all
