name: Run Tests

on:
- push
- workflow_dispatch

jobs:
  build_and_test:
    name: Test DAWN on ${{ matrix.os }}

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - name: Check out repository
      uses: actions/checkout@v4
      with:
        submodules: true
    - name: List BioCro files
      run: |
        cd biocro-lib
        git branch
        ls -lR src
    - name: Install xerces-c
      run: |
        sudo apt-get install -y libxerces-c-dev
    - name: Build all targets
      run: |
        cmake -B build -S .
        cmake --build build
    - name: Run Tests
      run: |
        cd build
        ctest
    - name: Upload Artifact
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: error_log
        path: build/Testing/Temporary/*
